cmake_minimum_required(VERSION 3.22)

if(NOT DEFINED INPUT_DIR OR INPUT_DIR STREQUAL "")
  message(FATAL_ERROR "INPUT_DIR is required")
endif()
if(NOT DEFINED OUTPUT_HEADER OR OUTPUT_HEADER STREQUAL "")
  message(FATAL_ERROR "OUTPUT_HEADER is required")
endif()

get_filename_component(INPUT_DIR "${INPUT_DIR}" ABSOLUTE)

file(GLOB_RECURSE BUILTIN_SQL_FILES "${INPUT_DIR}/*.sql")
list(SORT BUILTIN_SQL_FILES)

function(_to_pascal_case input_str output_var)
  string(REGEX REPLACE "[^A-Za-z0-9]+" ";" _tokens "${input_str}")
  set(_out "")
  foreach(_t IN LISTS _tokens)
    if(_t STREQUAL "")
      continue()
    endif()
    string(SUBSTRING "${_t}" 0 1 _first)
    string(LENGTH "${_t}" _len)
    if(_len GREATER 1)
      math(EXPR _rest_len "${_len} - 1")
      string(SUBSTRING "${_t}" 1 ${_rest_len} _rest)
    else()
      set(_rest "")
    endif()
    string(TOUPPER "${_first}" _first_u)
    string(TOLOWER "${_rest}" _rest_l)
    set(_out "${_out}${_first_u}${_rest_l}")
  endforeach()
  if(_out STREQUAL "")
    set(_out "Sql")
  endif()
  string(SUBSTRING "${_out}" 0 1 _c0)
  if(_c0 MATCHES "^[0-9]$")
    set(_out "_${_out}")
  endif()
  set(${output_var} "${_out}" PARENT_SCOPE)
endfunction()

get_filename_component(_out_dir "${OUTPUT_HEADER}" DIRECTORY)
file(MAKE_DIRECTORY "${_out_dir}")

set(_header "")
string(APPEND _header "#pragma once\n")
string(APPEND _header "#include <array>\n")
string(APPEND _header "#include <string_view>\n\n")
string(APPEND _header "namespace LinkuraLocal::HttpMockBackendBuiltInSql {\n")
string(APPEND _header "struct BuiltinSqlScript {\n")
string(APPEND _header "  std::string_view path;\n")
string(APPEND _header "  std::string_view sql;\n")
string(APPEND _header "};\n")

set(_schema_entries "")
set(_seed_entries "")
set(_schema_count 0)
set(_seed_count 0)
set(_delim "LL_SQL")

foreach(_f IN LISTS BUILTIN_SQL_FILES)
  file(RELATIVE_PATH _rel "${INPUT_DIR}" "${_f}")
  string(REPLACE "\\" "/" _rel "${_rel}")
  _to_pascal_case("${_rel}" _name_base)
  set(_name "${_name_base}Sql")

  file(READ "${_f}" _content)
  string(REPLACE "\r\n" "\n" _content "${_content}")
  string(REPLACE "\r" "\n" _content "${_content}")

  string(APPEND _header "\n")
  string(APPEND _header "inline constexpr std::string_view ${_name}View = R\"${_delim}(\n")
  string(APPEND _header "${_content}\n")
  string(APPEND _header ")${_delim}\";\n")
  string(APPEND _header "inline constexpr BuiltinSqlScript ${_name}Script{ \"${_rel}\", ${_name}View };\n")

  if(_rel MATCHES "^schema/")
    if(NOT _schema_entries STREQUAL "")
      string(APPEND _schema_entries ", ")
    endif()
    string(APPEND _schema_entries "${_name}Script")
    math(EXPR _schema_count "${_schema_count} + 1")
  elseif(_rel MATCHES "^seed/")
    if(NOT _seed_entries STREQUAL "")
      string(APPEND _seed_entries ", ")
    endif()
    string(APPEND _seed_entries "${_name}Script")
    math(EXPR _seed_count "${_seed_count} + 1")
  endif()
endforeach()

string(APPEND _header "\ninline constexpr std::array<BuiltinSqlScript, ${_schema_count}> SchemaScripts{ ${_schema_entries} };\n")
string(APPEND _header "inline constexpr std::array<BuiltinSqlScript, ${_seed_count}> SeedScripts{ ${_seed_entries} };\n")
string(APPEND _header "\n} // namespace LinkuraLocal::HttpMockBackendBuiltInSql\n")

file(WRITE "${OUTPUT_HEADER}" "${_header}")

message(STATUS "Generated builtin SQL header: ${OUTPUT_HEADER} (${BUILTIN_SQL_FILES})")
