-- Generated by backend/tools/generate_all.py
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS archive_detail (
    archives_id TEXT NOT NULL PRIMARY KEY,
    response_json TEXT NOT NULL,
    archive_url TEXT NOT NULL DEFAULT '',
    chapters TEXT NOT NULL DEFAULT '[]',
    characters TEXT NOT NULL DEFAULT '[]',
    content_code INTEGER NOT NULL DEFAULT 0,
    costume_ids TEXT NOT NULL DEFAULT '[]',
    current_camera_type INTEGER NOT NULL DEFAULT 0,
    current_play_time_second INTEGER NOT NULL DEFAULT 0,
    description TEXT NOT NULL DEFAULT '',
    gift_pt_rankings TEXT NOT NULL DEFAULT '[]',
    has_extra_admission INTEGER NOT NULL DEFAULT 0,
    live_location_id INTEGER NOT NULL DEFAULT 0,
    live_start_time TEXT NOT NULL DEFAULT '',
    selectable_camera_types TEXT NOT NULL DEFAULT '[]',
    ticket_rank INTEGER NOT NULL DEFAULT 0,
    timeline_ids TEXT NOT NULL DEFAULT '[]',
    timelines TEXT NOT NULL DEFAULT '[]',
    title TEXT NOT NULL DEFAULT '',
    total_gift_pt TEXT NOT NULL DEFAULT '',
    total_play_time_second INTEGER NOT NULL DEFAULT 0,
    unixtime_live_rec_started INTEGER NOT NULL DEFAULT 0,
    user_gift_pt INTEGER NOT NULL DEFAULT 0,
    user_gift_pt_ranking INTEGER NOT NULL DEFAULT 0,
    user_icon_parts_info TEXT NOT NULL DEFAULT '',
    video_url TEXT NOT NULL DEFAULT '',
    viewer_count INTEGER NOT NULL DEFAULT 0,
    enquetes TEXT NOT NULL DEFAULT '[]',
    gift_star_reward_segments TEXT NOT NULL DEFAULT '[]',
    gift_stars_threshold_for_extra_admission INTEGER NOT NULL DEFAULT 0,
    has_extra INTEGER NOT NULL DEFAULT 0,
    is_archive_published INTEGER NOT NULL DEFAULT 0,
    total_play_time_second_including_extra INTEGER NOT NULL DEFAULT 0,
    total_play_time_second_without_extra INTEGER NOT NULL DEFAULT 0,
    user_gift_pt_including_archive INTEGER NOT NULL DEFAULT 0,
    user_gift_pt_without_archive INTEGER NOT NULL DEFAULT 0,
    is_horizontal INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_archive_detail_title ON archive_detail(title);

CREATE TABLE IF NOT EXISTS card_detail (
    d_card_datas_id TEXT NOT NULL PRIMARY KEY,
    response_json TEXT NOT NULL,
    card_datas_id INTEGER NOT NULL DEFAULT 0,
    card_name TEXT NOT NULL DEFAULT '',
    style_level INTEGER NOT NULL DEFAULT 0,
    max_style_level INTEGER NOT NULL DEFAULT 0,
    limit_break_times INTEGER NOT NULL DEFAULT 0,
    max_limit_break_times INTEGER NOT NULL DEFAULT 0,
    card_parameters TEXT NOT NULL DEFAULT '[]',
    skill_list TEXT NOT NULL DEFAULT '[]',
    character_id INTEGER NOT NULL DEFAULT 0,
    generations_id INTEGER NOT NULL DEFAULT 0,
    series_type INTEGER NOT NULL DEFAULT 0,
    card_sort_order INTEGER NOT NULL DEFAULT 0,
    character_bonus TEXT NOT NULL DEFAULT '[]',
    is_evolve_possible INTEGER NOT NULL DEFAULT 0,
    is_evolve_max INTEGER NOT NULL DEFAULT 0,
    member_fan_level INTEGER NOT NULL DEFAULT 0,
    is_limit_break INTEGER NOT NULL DEFAULT 0,
    is_style_level_up INTEGER NOT NULL DEFAULT 0,
    rhythm_game_skill_list TEXT NOT NULL DEFAULT '[]'
);

CREATE INDEX IF NOT EXISTS idx_card_detail_card_datas_id ON card_detail(card_datas_id);
CREATE INDEX IF NOT EXISTS idx_card_detail_character_id ON card_detail(character_id);

CREATE TABLE IF NOT EXISTS character_info (
    character_id TEXT NOT NULL PRIMARY KEY,
    response_json TEXT NOT NULL,
    name_last TEXT NOT NULL DEFAULT '',
    name_first TEXT NOT NULL DEFAULT '',
    latin_alphabet_name_last TEXT NOT NULL DEFAULT '',
    latin_alphabet_name_first TEXT NOT NULL DEFAULT '',
    character_voice TEXT NOT NULL DEFAULT '',
    theme_color TEXT NOT NULL DEFAULT '',
    card_list TEXT NOT NULL DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS item (
    d_item_datas_id TEXT NOT NULL PRIMARY KEY,
    response_json TEXT NOT NULL,
    item_id INTEGER NOT NULL DEFAULT 0,
    item_type INTEGER NOT NULL DEFAULT 0,
    item_category INTEGER NOT NULL DEFAULT 0,
    rarity INTEGER NOT NULL DEFAULT 0,
    name TEXT NOT NULL DEFAULT '',
    name_furigana TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    effect_value INTEGER NOT NULL DEFAULT 0,
    limit_num INTEGER NOT NULL DEFAULT 0,
    requestable_num INTEGER NOT NULL DEFAULT 0,
    start_time TEXT NOT NULL DEFAULT '',
    end_time TEXT NOT NULL DEFAULT '',
    item_num INTEGER NOT NULL DEFAULT 0,
    limit_date_time TEXT,
    quest_list TEXT NOT NULL DEFAULT '[]',
    resource_file_name TEXT NOT NULL DEFAULT '',
    transition_scene TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_item_item_id ON item(item_id);
CREATE INDEX IF NOT EXISTS idx_item_item_type ON item(item_type);
CREATE INDEX IF NOT EXISTS idx_item_item_category ON item(item_category);
