from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import generate_archive_detail_sql as archive_detail
import generate_card_detail_sql as card_detail
import generate_character_info_sql as character_info
import generate_custom_setting as custom_setting
import generate_daily_quest_stage_sql as daily_quest_stage
import generate_deck_sql as deck
import generate_dream_quest_stage_sql as dream_quest_stage
import generate_learning_stage_sql as learning_stage
import generate_music_mastery_sql as music_mastery
import generate_home_get_home as home
import generate_music_list as music_list
import generate_music_sql as music_db
import generate_quest_stage_sql as quest_stage
import generate_rhythm_game_sql as rhythm_game
import generate_sticker_list as sticker_list
import generate_user_items as item

TOOLS_DIR = Path(__file__).resolve().parent
SCHEMA_SQL = TOOLS_DIR.parent / "schema" / "001_init.sql"
SEED_SQL = TOOLS_DIR.parent / "seed" / "001_init.sql"

GENERATOR_NOTE = "-- Generated by backend/tools/generate_all.py"


def main() -> None:
    print("=== Generate JSON (YAML -> JSON) ===")
    card_detail.generate_json()
    character_info.generate_json()
    custom_setting.generate_json()
    home.generate_json()
    music_list.generate_json()
    sticker_list.generate_json()
    item.generate_json()

    print("=== Generate SQL ===")
    schema_parts = [
        GENERATOR_NOTE,
        "PRAGMA foreign_keys = ON;",
        "",
        archive_detail.generate_schema_ddl(),
        "",
        card_detail.generate_schema_ddl(),
        "",
        character_info.generate_schema_ddl(),
        "",
        item.generate_schema_ddl(),
        "",
        deck.generate_schema_ddl(),
        "",
        rhythm_game.generate_schema_ddl(),
        "",
        quest_stage.generate_schema_ddl(),
        "",
        daily_quest_stage.generate_schema_ddl(),
        "",
        dream_quest_stage.generate_schema_ddl(),
        "",
        learning_stage.generate_schema_ddl(),
        "",
        music_mastery.generate_schema_ddl(),
        "",
        music_db.generate_schema_ddl(),
        "",
    ]
    SCHEMA_SQL.write_text("\n".join(schema_parts), encoding="utf-8", newline="\n")
    print(f"  Written: {SCHEMA_SQL}")

    seed_lines: list[str] = [
        GENERATOR_NOTE,
        "BEGIN IMMEDIATE;",
        *archive_detail.generate_seed_statements(),
        *card_detail.generate_seed_statements(),
        *character_info.generate_seed_statements(),
        *item.generate_seed_statements(),
        *deck.generate_seed_statements(),
        *rhythm_game.generate_seed_statements(),
        *quest_stage.generate_seed_statements(),
        *daily_quest_stage.generate_seed_statements(),
        *dream_quest_stage.generate_seed_statements(),
        *learning_stage.generate_seed_statements(),
        *music_mastery.generate_seed_statements(),
        *music_db.generate_seed_statements(),
        "COMMIT;",
        "",
    ]
    SEED_SQL.write_text("\n".join(seed_lines), encoding="utf-8", newline="\n")
    print(f"  Written: {SEED_SQL}")

    print("=== Done ===")


if __name__ == "__main__":
    main()
