from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import generate_archive_detail_sql as archive_detail
import generate_card_detail_sql as card_detail
import generate_character_info_sql as character_info

ROOT = Path(__file__).resolve().parents[4]
SCHEMA_SQL = ROOT / "LinkuraLocalify" / "http-mock" / "backend" / "schema" / "001_init.sql"
SEED_SQL = ROOT / "LinkuraLocalify" / "http-mock" / "backend" / "seed" / "001_init.sql"

GENERATOR_NOTE = "-- Generated by backend/tools/generate_all.py"


def main() -> None:
    schema_parts = [
        GENERATOR_NOTE,
        "PRAGMA foreign_keys = ON;",
        "",
        archive_detail.generate_schema_ddl(),
        "",
        card_detail.generate_schema_ddl(),
        "",
        character_info.generate_schema_ddl(),
        "",
    ]
    SCHEMA_SQL.write_text("\n".join(schema_parts), encoding="utf-8", newline="\n")
    print(f"Written: {SCHEMA_SQL}")

    seed_lines: list[str] = [
        GENERATOR_NOTE,
        "BEGIN IMMEDIATE;",
        *archive_detail.generate_seed_statements(),
        *card_detail.generate_seed_statements(),
        *character_info.generate_seed_statements(),
        "COMMIT;",
        "",
    ]
    SEED_SQL.write_text("\n".join(seed_lines), encoding="utf-8", newline="\n")
    print(f"Written: {SEED_SQL}")


if __name__ == "__main__":
    main()
